apiVersion: apps/v1
kind: Deployment
metadata:
  name: churn-prediction-ui
  namespace: default
  labels:
    app: churn-prediction-ui
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: churn-prediction-ui
  template:
    metadata:
      labels:
        app: churn-prediction-ui
        tier: frontend
    spec:
      containers:
      - name: nginx
        image: churn-prediction-ui:latest
        ports:
        - containerPort: 80
          name: http
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: churn-prediction-ui-service
  namespace: default
  labels:
    app: churn-prediction-ui
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: churn-prediction-ui
---
# Optional: NodePort service for external access
apiVersion: v1
kind: Service
metadata:
  name: churn-prediction-ui-nodeport
  namespace: default
  labels:
    app: churn-prediction-ui
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
    protocol: TCP
    name: http
  selector:
    app: churn-prediction-ui
---
# Optional: Ingress for domain-based access
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: churn-prediction-ui-ingress
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: churn-ui.local  # Replace with your domain
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: churn-prediction-ui-service
            port:
              number: 80 