name: Deploy UI Frontend to EKS

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'production'
        type: choice
        options:
        - production
        - staging
      api_endpoint:
        description: 'FastAPI endpoint URL (e.g., http://NODE_IP:30080)'
        required: false
        type: string
      force_rebuild:
        description: 'Force rebuild Docker image'
        required: false
        default: false
        type: boolean

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: churn-prediction-ui
  EKS_CLUSTER_NAME: churnmodel
  K8S_NAMESPACE: default

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}
        
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      
    - name: Create ECR repository if it doesn't exist
      run: |
        aws ecr describe-repositories --repository-names $ECR_REPOSITORY --region $AWS_REGION || \
        aws ecr create-repository --repository-name $ECR_REPOSITORY --region $AWS_REGION \
          --image-scanning-configuration scanOnPush=true \
          --encryption-configuration encryptionType=AES256
          
    - name: Auto-detect API endpoint
      id: detect-api
      run: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        chmod +x kubectl
        sudo mv kubectl /usr/local/bin/
        
        aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
        
        NODE_IP=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="ExternalIP")].address}')
        if [ -z "$NODE_IP" ]; then
          NODE_IP=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')
        fi
        
        if [ -n "${{ github.event.inputs.api_endpoint }}" ]; then
          API_ENDPOINT="${{ github.event.inputs.api_endpoint }}"
        else
          API_ENDPOINT="http://$NODE_IP:30080"
        fi
        
        echo "API_ENDPOINT=$API_ENDPOINT" >> $GITHUB_ENV
        echo "Using API endpoint: $API_ENDPOINT"
        
    - name: Update UI configuration
      run: |
        cd ui-deployment
        
        echo "Updating API endpoint in script.js..."
        sed -i "s|const API_BASE_URL = .*|const API_BASE_URL = '${{ env.API_ENDPOINT }}';|g" script.js
        
        echo "Updated API endpoint:"
        grep "API_BASE_URL" script.js
        
    - name: Build, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd ui-deployment
        
        echo "Building Docker image..."
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG $ECR_REGISTRY/$ECR_REPOSITORY:latest
        
        echo "Pushing images to ECR..."
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest
        
        echo "IMAGE_URI=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_ENV
        
    - name: Update kubeconfig
      run: |
        aws eks update-kubeconfig --region $AWS_REGION --name $EKS_CLUSTER_NAME
        
    - name: Update Kubernetes manifests
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        cd ui-deployment
        
        echo "Updating image in deployment manifest..."
        sed -i "s|image: .*|image: $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG|g" k8s-deployment.yaml
        
        # echo "Adding deployment timestamp..."
        # sed -i "/metadata:/a\\  annotations:\n    deployment.kubernetes.io/revision: \"$(date +%s)\"" k8s-deployment.yaml
        
    - name: Deploy to EKS
      run: |
        cd ui-deployment
        
        echo "Applying deployment..."
        kubectl apply -f k8s-deployment.yaml --namespace=$K8S_NAMESPACE
        
        echo "Waiting for rollout to complete..."
        kubectl rollout status deployment/churn-prediction-ui --namespace=$K8S_NAMESPACE --timeout=300s
        
    - name: Verify deployment
      run: |
        echo "Checking deployment status..."
        kubectl get pods -l app=churn-prediction-ui --namespace=$K8S_NAMESPACE
        kubectl get services --namespace=$K8S_NAMESPACE
        
        echo "Waiting for pods to be ready..."
        kubectl wait --for=condition=ready pod -l app=churn-prediction-ui --namespace=$K8S_NAMESPACE --timeout=120s
        
        NODE_IP=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="ExternalIP")].address}')
        if [ -z "$NODE_IP" ]; then
          NODE_IP=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')
        fi
        
        echo "Deployment successful!"
        echo "UI Application: http://$NODE_IP:30081"
        echo "API Connection: ${{ env.API_ENDPOINT }}"
        
    - name: Health check
      run: |
        NODE_IP=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="ExternalIP")].address}')
        if [ -z "$NODE_IP" ]; then
          NODE_IP=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')
        fi
        
        echo "Waiting for service to be ready..."
        sleep 15
        
        echo "Running health checks..."
        for i in {1..5}; do
          if curl -f -s "http://$NODE_IP:30081" > /dev/null; then
            echo "UI health check passed!"
            break
          else
            echo "UI health check attempt $i/5 failed, retrying..."
            sleep 10
          fi
        done
        
        echo "Testing API connectivity..."
        if curl -f -s "${{ env.API_ENDPOINT }}/health" > /dev/null; then
          echo "API connectivity verified!"
        else
          echo "Warning: API connectivity issue - check API endpoint"
        fi
        
    - name: Generate deployment summary
      if: always()
      run: |
        echo "## UI Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "- **Environment**: ${{ github.event.inputs.environment }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Image**: ${{ env.IMAGE_URI }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Cluster**: ${{ env.EKS_CLUSTER_NAME }}" >> $GITHUB_STEP_SUMMARY
        echo "- **Namespace**: ${{ env.K8S_NAMESPACE }}" >> $GITHUB_STEP_SUMMARY
        echo "- **API Endpoint**: ${{ env.API_ENDPOINT }}" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        NODE_IP=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="ExternalIP")].address}')
        if [ -z "$NODE_IP" ]; then
          NODE_IP=$(kubectl get nodes -o jsonpath='{.items[0].status.addresses[?(@.type=="InternalIP")].address}')
        fi
        
        echo "### Access URLs" >> $GITHUB_STEP_SUMMARY
        echo "- **UI Application**: http://$NODE_IP:30081" >> $GITHUB_STEP_SUMMARY
        echo "- **API Backend**: ${{ env.API_ENDPOINT }}" >> $GITHUB_STEP_SUMMARY
        echo "- **API Docs**: ${{ env.API_ENDPOINT }}/docs" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        
        echo "### Pod Status" >> $GITHUB_STEP_SUMMARY
        kubectl get pods -l app=churn-prediction-ui --namespace=$K8S_NAMESPACE >> $GITHUB_STEP_SUMMARY 